# Generated by Django 4.2.29 on 2026-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='outcome',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
